# Generated by Django 4.2 on 2024-07-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='department',
            field=models.CharField(blank=True, choices=[('1st_dep', 'سكرتارية السيد المدير'), ('2nd_dep', 'سكرتارية السيد النائب'), ('3rd_dep', 'التعليم'), ('4th_dep', 'الاقسام التعليمية'), ('5th_dep', 'كتيبة الطلبة'), ('6th_dep', 'الامداد و الاصلاح'), ('7th_dep', 'نظم المعلومات'), ('8th_dep', 'اركان حرب  الكلية'), ('9th_dep', 'الامن'), ('10th_dep', 'الشئون الادارية'), ('11th_dep', 'المسجل'), ('12th_dep', 'شئون العاملين'), ('13th_dep', 'النقطة الطبية'), ('14th_dep', 'القبة السماوية'), ('15th_dep', 'الهنجر'), ('16th_dep', 'منوب عمليات'), ('17th_dep', 'الحملة'), ('18th_dep', 'التحويلة'), ('19th_dep', 'السلاح'), ('22th_dep', 'فوج الجنود')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='degree',
            field=models.CharField(choices=[('soldier', 'جندي'), ('Corporal', 'عريف'), ('Sergeant', 'رقيب'), ('staff_Sergeant', 'رقيب أول'), ('assistant', 'مساعد'), ('First_Assistant', 'مساعد أول'), ('lieutenant', 'ملازم'), ('first_lieutenant', 'ملازم أول'), ('captain', 'نقيب'), ('major', 'رائد'), ('lieutenant_colonel', 'مقدم'), ('Colonel', 'عقيد'), ('Dean', 'عميد'), ('General', 'لواء')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(choices=[('1st_dep', 'سكرتارية السيد المدير'), ('2nd_dep', 'سكرتارية السيد النائب'), ('3rd_dep', 'التعليم'), ('4th_dep', 'الاقسام التعليمية'), ('5th_dep', 'كتيبة الطلبة'), ('6th_dep', 'الامداد و الاصلاح'), ('7th_dep', 'نظم المعلومات'), ('8th_dep', 'اركان حرب  الكلية'), ('9th_dep', 'الامن'), ('10th_dep', 'الشئون الادارية'), ('11th_dep', 'المسجل'), ('12th_dep', 'شئون العاملين'), ('13th_dep', 'النقطة الطبية'), ('14th_dep', 'القبة السماوية'), ('15th_dep', 'الهنجر'), ('16th_dep', 'منوب عمليات'), ('17th_dep', 'الحملة'), ('18th_dep', 'التحويلة'), ('19th_dep', 'السلاح'), ('22th_dep', 'فوج الجنود')], max_length=100),
        ),
    ]
