# Generated by Django 4.2.14 on 2024-07-31 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0003_remove_meeting_member_alter_meeting_meeting_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='scheduled_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
