# Generated by Django 4.2.14 on 2024-08-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0005_alter_meeting_status_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('vice_manager', 'Vice Manager')], max_length=20),
        ),
    ]
