# Generated by Django 4.2.14 on 2024-08-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0006_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='manager', max_length=20),
        ),
    ]
